# Generated by Django 5.2.3 on 2025-06-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('risk_level', models.CharField(max_length=20)),
                ('appointment', models.CharField(max_length=20)),
                ('condition', models.CharField(max_length=100)),
                ('wait_time', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
