# Generated by Django 5.2.3 on 2025-06-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_patient_address_patient_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='abnormal_pap',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='first_sexual_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='hpv_positive',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='sexual_partners',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='smoking',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='stds_history',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
