# Generated by Django 5.1.7 on 2025-07-02 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_patient_risk_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='abnormal_pap',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='first_sexual_age',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hpv_positive',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='sexual_partners',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='smoking',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='stds_history',
        ),
    ]
