# Generated by Django 5.1.7 on 2025-07-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_patient_abnormal_pap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessmenthistory',
            name='abnormal_pap',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskassessmenthistory',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskassessmenthistory',
            name='first_sexual_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskassessmenthistory',
            name='hpv_positive',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskassessmenthistory',
            name='insurance',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskassessmenthistory',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='riskassessmenthistory',
            name='screening_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='riskassessmenthistory',
            name='sexual_partners',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskassessmenthistory',
            name='smoking',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskassessmenthistory',
            name='stds_history',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskassessmenthistory',
            name='total_risk_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskassessmenthistory',
            name='years_sexually_active',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riskassessmenthistory',
            name='risk_score',
            field=models.FloatField(),
        ),
    ]
