# Generated by Django 5.1.7 on 2025-07-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_inventory_cost_inventory_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cost',
            name='facility',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cost',
            name='insurance_copay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cost',
            name='nhif_covered',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cost',
            name='out_of_pocket',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cost',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
