# Generated by Django 5.1.7 on 2025-07-02 21:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_cost_category_cost_facility_cost_insurance_copay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
