# Generated by Django 5.1.7 on 2025-07-02 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_cost_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_rooms', to='api.patient'),
        ),
    ]
